import { randomUUID } from 'node:crypto';
import { PendingWorklistOrder } from './medsysClient';

// DICOM 2.25.{uuid-as-decimal-integer} is a valid UID per Part 5 Annex B.
export function generateStudyInstanceUid(): string {
  const hex = randomUUID().replace(/-/g, '');
  const asBigInt = BigInt('0x' + hex);
  return `2.25.${asBigInt.toString()}`;
}

const pad2 = (n: number) => String(n).padStart(2, '0');

function dicomDate(input: string | Date): string {
  const d = typeof input === 'string' ? new Date(input) : input;
  if (Number.isNaN(d.getTime())) return '';
  return `${d.getFullYear()}${pad2(d.getMonth() + 1)}${pad2(d.getDate())}`;
}

function dicomTime(input: string | Date): string {
  const d = typeof input === 'string' ? new Date(input) : input;
  if (Number.isNaN(d.getTime())) return '120000';
  return `${pad2(d.getHours())}${pad2(d.getMinutes())}${pad2(d.getSeconds())}`;
}

function dicomPatientName(last: string, first: string): string {
  // PN VR. Format: family^given^middle^prefix^suffix
  const safe = (s: string) => (s || '').replace(/[\^\\]/g, ' ').trim();
  return `${safe(last)}^${safe(first)}^`;
}

function dicomPriority(p: string): string {
  switch ((p || '').toLowerCase()) {
    case 'stat':    return 'STAT';
    case 'urgent':  return 'HIGH';
    case 'routine': return 'ROUTINE';
    default:        return 'ROUTINE';
  }
}

/**
 * Build a dump2dcm-format text file for the given order. Returns:
 *   { dumpText, studyInstanceUid, accessionNumber }
 *
 * The dump file is then converted to a binary .wl by dump2dcm.exe and dropped
 * in the orthanc-worklists Database folder. Modalities query MWL and get this
 * patient/order back.
 */
export function buildWorklistDump(order: PendingWorklistOrder): {
  dumpText: string;
  studyInstanceUid: string;
  accessionNumber: string;
} {
  const studyUid = generateStudyInstanceUid();
  const scheduledDate = dicomDate(order.scheduled_datetime);
  const scheduledTime = dicomTime(order.scheduled_datetime);
  const dob = order.patient.date_of_birth ? dicomDate(order.patient.date_of_birth) : '';
  const patientName = dicomPatientName(order.patient.last_name, order.patient.first_name);

  // dump2dcm format. Indentation matters inside sequences (use 2 spaces per level).
  const lines = [
    `# Generated by medsys-bridge for order ${order.order_id}`,
    `(0008,0005) CS [ISO_IR 100]                      # SpecificCharacterSet`,
    `(0008,0050) SH [${order.accession_number}]       # AccessionNumber`,
    `(0010,0010) PN [${patientName}]                  # PatientName`,
    `(0010,0020) LO [${order.patient.patient_number}] # PatientID`,
    `(0010,0030) DA [${dob}]                          # PatientBirthDate`,
    `(0010,0040) CS [${order.patient.sex}]            # PatientSex`,
    `(0020,000d) UI [${studyUid}]                     # StudyInstanceUID`,
    `(0032,1060) LO [${escapeBracket(order.requested_procedure_description)}] # RequestedProcedureDescription`,
    `(0040,1001) SH [RP${order.order_id}]             # RequestedProcedureID`,
    `(0040,1003) SH [${dicomPriority(order.priority)}] # RequestedProcedurePriority`,
    `(0040,0100) SQ (Sequence with undefined length)  # ScheduledProcedureStepSequence`,
    `(fffe,e000) na (Item with undefined length)`,
    `  (0008,0060) CS [${order.modality}]             # Modality`,
    `  (0040,0001) AE [${order.scheduled_station_ae_title}] # ScheduledStationAETitle`,
    `  (0040,0002) DA [${scheduledDate}]              # ScheduledProcedureStepStartDate`,
    `  (0040,0003) TM [${scheduledTime}]              # ScheduledProcedureStepStartTime`,
    `  (0040,0006) PN [${escapeBracket(order.referring_physician || '')}] # ScheduledPerformingPhysicianName`,
    `  (0040,0007) LO [${escapeBracket(order.study_description)}] # ScheduledProcedureStepDescription`,
    `  (0040,0009) SH [${order.scheduled_procedure_step_id}] # ScheduledProcedureStepID`,
    `(fffe,e00d) na (ItemDelimitationItem)`,
    `(fffe,e0dd) na (SequenceDelimitationItem)`,
    ``,
  ];

  return {
    dumpText: lines.join('\n'),
    studyInstanceUid: studyUid,
    accessionNumber: order.accession_number,
  };
}

function escapeBracket(s: string): string {
  // dump2dcm uses [] to delimit values — strip any embedded brackets.
  return (s || '').replace(/[\[\]\\]/g, ' ').trim();
}
